#!/usr/bin/env bash
# iPod — Podcast → Yoto · one-shot installer.
#
# Usage (from the internet):
#   curl -fsSL https://raw.githubusercontent.com/jaudoux/ipod/main/install.sh | bash
#
# Re-running the script updates an existing install.
#
# Overrides (env vars):
#   IPOD_HOME      Install directory (default: $HOME/.local/share/ipod)
#   IPOD_BIN_DIR   Where the `ipod` launcher lands (default: $HOME/.local/bin)
#   IPOD_REPO      Git URL to clone from
#   IPOD_REF       Branch/tag/commit to check out (default: main)

set -euo pipefail

REPO_URL="${IPOD_REPO:-https://github.com/jaudoux/ipod.git}"
REF="${IPOD_REF:-main}"
INSTALL_DIR="${IPOD_HOME:-$HOME/.local/share/ipod}"
BIN_DIR="${IPOD_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/ipod"
VENV_DIR="$INSTALL_DIR/.venv"
MIN_PY_MINOR=10  # Python 3.10+ (code uses PEP 604 `X | None` unions)

# ---------------------------------------------------------------- output

if [ -t 1 ]; then
    BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
    YELLOW=$'\033[33m'; CYAN=$'\033[36m'; RESET=$'\033[0m'
else
    BOLD=""; DIM=""; RED=""; GREEN=""; YELLOW=""; CYAN=""; RESET=""
fi
say()  { printf "%s➜%s %s\n" "$CYAN" "$RESET" "$*"; }
ok()   { printf "%s✓%s %s\n" "$GREEN" "$RESET" "$*"; }
warn() { printf "%s⚠%s %s\n" "$YELLOW" "$RESET" "$*"; }
die()  { printf "%s✗%s %s\n" "$RED" "$RESET" "$*" >&2; exit 1; }

# ---------------------------------------------------------------- prerequisites

detect_pkg_mgr() {
    if   command -v brew >/dev/null 2>&1; then echo "brew"
    elif command -v apt-get >/dev/null 2>&1; then echo "apt"
    elif command -v dnf >/dev/null 2>&1; then echo "dnf"
    elif command -v pacman >/dev/null 2>&1; then echo "pacman"
    else echo ""
    fi
}

install_hint() {
    # $1 = tool name ; $2 = brew package ; $3 = apt package ; $4 = dnf package ; $5 = pacman package
    local mgr; mgr="$(detect_pkg_mgr)"
    case "$mgr" in
        brew)   echo "brew install $2" ;;
        apt)    echo "sudo apt-get install -y $3" ;;
        dnf)    echo "sudo dnf install -y $4" ;;
        pacman) echo "sudo pacman -S --needed $5" ;;
        *)      echo "install $1 with your package manager" ;;
    esac
}

pick_python() {
    local candidates=("python3.13" "python3.12" "python3.11" "python3.10" "python3")
    local bin minor
    for bin in "${candidates[@]}"; do
        if command -v "$bin" >/dev/null 2>&1; then
            minor="$("$bin" -c 'import sys; print(sys.version_info.minor)' 2>/dev/null || echo 0)"
            if [ "$minor" -ge "$MIN_PY_MINOR" ]; then
                echo "$bin"
                return 0
            fi
        fi
    done
    return 1
}

check_prereqs() {
    command -v git >/dev/null 2>&1 \
        || die "git is required. $(install_hint git git git git git)"

    PYTHON_BIN="$(pick_python)" \
        || die "Python 3.$MIN_PY_MINOR+ is required. $(install_hint python3 python python3 python3 python)"
    ok "Using $($PYTHON_BIN -V) at $PYTHON_BIN"

    if ! command -v ffmpeg >/dev/null 2>&1; then
        warn "ffmpeg not found — ad-trim and fast audio processing will fall back to pure-Python (slower and needs libav)."
        warn "Install it with: $(install_hint ffmpeg ffmpeg ffmpeg ffmpeg ffmpeg)"
    else
        ok "Found ffmpeg at $(command -v ffmpeg)"
    fi
}

# ---------------------------------------------------------------- install

clone_or_update() {
    if [ -d "$INSTALL_DIR/.git" ]; then
        say "Updating existing install at $INSTALL_DIR"
        git -C "$INSTALL_DIR" fetch --quiet origin
        git -C "$INSTALL_DIR" checkout --quiet "$REF"
        git -C "$INSTALL_DIR" reset --hard --quiet "origin/$REF" 2>/dev/null \
            || git -C "$INSTALL_DIR" pull --quiet --ff-only
    elif [ -e "$INSTALL_DIR" ] && [ ! -d "$INSTALL_DIR" ]; then
        die "$INSTALL_DIR exists and is not a directory."
    elif [ -d "$INSTALL_DIR" ] && [ -n "$(ls -A "$INSTALL_DIR" 2>/dev/null)" ]; then
        die "$INSTALL_DIR is not empty and not a git clone. Remove it or set IPOD_HOME."
    else
        say "Cloning $REPO_URL into $INSTALL_DIR"
        mkdir -p "$(dirname "$INSTALL_DIR")"
        git clone --quiet --branch "$REF" "$REPO_URL" "$INSTALL_DIR"
    fi
}

setup_venv() {
    if [ ! -d "$VENV_DIR" ]; then
        say "Creating virtualenv in $VENV_DIR"
        "$PYTHON_BIN" -m venv "$VENV_DIR"
    fi
    say "Installing Python dependencies"
    # --upgrade keeps us idempotent on re-run.
    "$VENV_DIR/bin/pip" install --quiet --upgrade pip
    "$VENV_DIR/bin/pip" install --quiet --upgrade -r "$INSTALL_DIR/requirements.txt"
}

write_launcher() {
    mkdir -p "$BIN_DIR"
    cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by install.sh. Runs iPod from its isolated virtualenv.
exec "$VENV_DIR/bin/python" "$INSTALL_DIR/ipod.py" "\$@"
EOF
    chmod +x "$LAUNCHER"
    ok "Launcher written to $LAUNCHER"
}

path_hint() {
    case ":$PATH:" in
        *":$BIN_DIR:"*) return 0 ;;
    esac
    warn "$BIN_DIR is not on your PATH."
    local rc
    case "${SHELL##*/}" in
        zsh)  rc="$HOME/.zshrc" ;;
        bash) rc="$HOME/.bashrc" ;;
        fish) rc="$HOME/.config/fish/config.fish" ;;
        *)    rc="your shell's rc file" ;;
    esac
    if [ "${SHELL##*/}" = "fish" ]; then
        echo "    Add this line to $rc:"
        echo "        fish_add_path $BIN_DIR"
    else
        echo "    Add this line to $rc:"
        echo "        export PATH=\"$BIN_DIR:\$PATH\""
    fi
    echo "    Or run iPod directly: $LAUNCHER"
}

main() {
    printf "%s%siPod installer%s\n" "$BOLD" "$CYAN" "$RESET"
    printf "%s  repo: %s @ %s%s\n" "$DIM" "$REPO_URL" "$REF" "$RESET"
    printf "%s  into: %s%s\n\n" "$DIM" "$INSTALL_DIR" "$RESET"

    check_prereqs
    clone_or_update
    setup_venv
    write_launcher

    printf "\n%sInstalled.%s Next steps:\n" "$GREEN$BOLD" "$RESET"
    echo "  1. Grab a Yoto Public Client ID at https://dashboard.yoto.dev"
    echo "  2. Run: ipod"
    echo "     (first run prompts for the Client ID and opens the Yoto device-auth flow)"
    echo
    path_hint
}

main "$@"
